# Generated by Django 5.0.4 on 2024-04-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
